blank_issues_enabled: true
contact_links:
  - name: 主页预设反馈
    url: https://github.com/Hex-Dragon/PCL2/discussions/categories/自定义主页
    about: 提交与预设的主页（设置 → 个性化 → 主页预设）中的具体内容相关的反馈
  - name: 帮助文档反馈
    url: https://github.com/LTCatt/PCL2Help/issues
    about: 提交与 PCL 帮助文档（更多 → 帮助）中的具体内容相关的反馈
  - name: 提问 / 讨论
    url: https://github.com/PCL-Community/PCL2-CE/discussions/new
    about: 我想问问或谈谈关于社区版的事情...
