name: PR Automation

on:
  pull_request:
    types: [closed, reopened, opened]

jobs:
  handle_pr_events:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      
      - name: Remove old labels on merge
        if: github.event.action == 'closed' && github.event.pull_request.merged
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.BOT }}
          labels: |
            â­• ç­‰å¾…å¤„ç†
            ğŸš§ æ­£åœ¨å¤„ç†
            ğŸ•‘ ç­‰å¾…åˆå¹¶
            ğŸ•‘ ç­‰å¾…å‰ç½®

      - name: Add completed label
        if: github.event.action == 'closed' && github.event.pull_request.merged
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.BOT }}
          labels: ğŸ‘Œ å®Œæˆ

      
      - name: Clean labels on reopen
        if: github.event.action == 'reopened'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.BOT }}
          labels: |
            âŒ å¿½ç•¥
            âŒ æ‹’ç» / æ”¾å¼ƒ
            âŒ æš‚æ— è®¡åˆ’
            âŒ ç¬¬ä¸‰æ–¹
            â­• ç­‰å¾…å¤„ç†
            âŒ é‡å¤
      - name: Request team review
        if: github.event.action == 'opened'
        uses: actions/github-script@v7
        env:
          BOT_TOKEN: ${{ secrets.BOT }}
        with:
          script: |
            try {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                team_reviewers: ['developers']
              });
            } catch (error) {}
