name: PR Automation

on:
  pull_request:
    types: [closed, reopened, labeled]

jobs:
  pr_automation:
    runs-on: ubuntu-latest
    steps:
      - name: Auto close PR
        if: |
          github.event_name == 'pull_request' &&
          github.event.action == 'labeled' &&
          contains(
            'âŒ å¿½ç•¥,âŒ æ‹’ç» / æ”¾å¼ƒ,âŒ æš‚æ— è®¡åˆ’,âŒ ç¬¬ä¸‰æ–¹,âŒ é‡å¤,ğŸ˜‚ ç§»äº¤ä¸Šæ¸¸',
            github.event.label.name
          )
        env:
          GH_TOKEN: ${{ secrets.BOT }}
          PR_NUMBER: ${{ github.event.number }}
        run: gh pr close $PR_NUMBER

      - name: Cleanup merged PR
        if: github.event.action == 'closed' && github.event.pull_request.merged
        env:
          GH_TOKEN: ${{ secrets.BOT }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # åˆ é™¤æ—§æ ‡ç­¾
          printf '%s\n' 'â­• ç­‰å¾…å¤„ç†' 'ğŸš§ æ­£åœ¨å¤„ç†' 'ğŸ•‘ ç­‰å¾…åˆå¹¶' 'ğŸ•‘ ç­‰å¾…å‰ç½®' | while read -r label; do
            gh issue edit $PR_NUMBER --remove-label "$label" || true
          done
          
          # æ·»åŠ å®Œæˆæ ‡ç­¾
          gh issue edit $PR_NUMBER --add-label "ğŸ‘Œ å®Œæˆ"

      - name: Cleanup reopened PR
        if: github.event.action == 'reopened'
        env:
          GH_TOKEN: ${{ secrets.BOT }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # æ¸…ç†æ‹’ç»ç±»æ ‡ç­¾
          printf '%s\n' 'âŒ å¿½ç•¥' 'âŒ æ‹’ç» / æ”¾å¼ƒ' 'âŒ æš‚æ— è®¡åˆ’' 'âŒ ç¬¬ä¸‰æ–¹' 'âŒ é‡å¤' | while read -r label; do
            gh issue edit $PR_NUMBER --remove-label "$label" || true
          done