name: Issue Reopened
run-name: '#${{ github.event.issue.number }} ${{ github.event.issue.title }}'

on:
  issues:
    types: [reopened]

jobs:
  issue-reopened:
    runs-on: ubuntu-latest
    steps:
      - name: Remove labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: '${{ secrets.BOT }}'
          labels: 'ğŸ‘Œ å®Œæˆ,âŒ å¿½ç•¥,âŒ æ‹’ç» / æ”¾å¼ƒ,âŒ æš‚æ— è®¡åˆ’,âŒ ç¬¬ä¸‰æ–¹,âŒ é‡å¤,ğŸ˜‚ ç§»äº¤ä¸Šæ¸¸'