name: Issues Similarity Analysis

on:
  issues:
    types: [opened, edited]

jobs:
  similarity-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Issues Similarity Analysis
        uses: actions-cool/issues-similarity-analysis@v1.3.2
        with:
          filter-threshold: 0.75
          comment-title: '### 反馈重复性检测 | Issues Similarity Analysis'
          comment-body: '${index}. ${similarity} #${number}'
          show-footer: false
          show-mentioned: true
