name: Reusable Build

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
      architecture:
        required: true
        type: string

jobs:
  build:
    name: Build ${{ inputs.configuration }}-${{ inputs.architecture }}
    runs-on: windows-latest
    env:
      LANG: en_US.UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set Describe
        shell: bash
        run: |
          describe=`git describe --tags --always`
          echo "describe=$describe" >> $GITHUB_ENV

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: ${{ inputs.architecture }}

      - name: Update Help
        run: |
          cd ..
          git clone https://github.com/PCL-Community/PCL2CEHelp -b master --single-branch --depth 1
          cd PCL2CEHelp
          rm -Force -r *.*
          Compress-Archive -Path .\* -DestinationPath .\Help.zip
          Copy-Item -Path .\Help.zip -Destination "${{ github.workspace }}\Plain Craft Launcher 2\Resources\Help.zip" -Force
          cd ..
          rm -Force -r .\PCL2CEHelp
          cd ${{ GITHUB.WORKSPACE }}

      - name: Restore NuGet Packages
        run: nuget restore "Plain Craft Launcher 2\Plain Craft Launcher 2.vbproj" -PackagesDirectory "packages"

      - name: Replace Secrets and Commit Hash
        run: |
          (gc "Plain Craft Launcher 2\Modules\ModSecret.vb") -replace 'Public Const OAuthClientId As String = ""', 'Public Const OAuthClientId As String = "${{ secrets.CLIENT_ID }}"' | Out-File "Plain Craft Launcher 2\Modules\ModSecret.vb"
          (gc "Plain Craft Launcher 2\Modules\ModSecret.vb") -replace 'Public Const CurseForgeAPIKey As String = ""', 'Public Const CurseForgeAPIKey As String = "${{ secrets.CURSEFORGE_API_KEY }}"' | Out-File "Plain Craft Launcher 2\Modules\ModSecret.vb"
          (gc "Plain Craft Launcher 2\Modules\ModSecret.vb") -replace 'Public Const LittleSkinClientId As String = ""', 'Public Const LittleSkinClientId As String = "${{ secrets.LITTLESKIN_CLIENT_ID }}"' | Out-File "Plain Craft Launcher 2\Modules\ModSecret.vb"
          (gc "Plain Craft Launcher 2\Modules\ModSecret.vb") -replace 'Public Const TelemetryKey As String = ""', 'Public Const TelemetryKey As String = "${{ secrets.TELEMETRY_KEY }}"' | Out-File "Plain Craft Launcher 2\Modules\ModSecret.vb"
          (gc "Plain Craft Launcher 2\Modules\Base\ModBase.vb") -replace 'Public Const CommitHash As String = "native"', 'Public Const CommitHash As String = "${{ github.sha }}"' | Out-File "Plain Craft Launcher 2\Modules\Base\ModBase.vb"
          (gc "Plain Craft Launcher 2\Pages\PageOther\PageOtherAbout.xaml") -replace 'https://github.com/PCL-Community/PCL2-CE', 'https://github.com/PCL-Community/PCL2-CE/tree/${{ github.sha }}' | Out-File "Plain Craft Launcher 2\Pages\PageOther\PageOtherAbout.xaml"

      - name: Build
        run: |
          chcp 65001
          $PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          msbuild "Plain Craft Launcher 2\Plain Craft Launcher 2.vbproj" -t:Rebuild -p:Configuration=${{ inputs.configuration }} -p:Platform=${{ inputs.architecture }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PCL2_CE_${{ inputs.configuration }}_${{ inputs.architecture }}
          path: Plain Craft Launcher 2\obj\${{ inputs.architecture }}\${{ inputs.configuration }}\Plain Craft Launcher 2.exe